---
- name: Install CUPS ad drivers
  package:
    name:
      - ghostscript
      - gsfonts
      - cups
      - cups-pdf
      - gutenprint
      - hplip
    state: present

- name: Add print admin group
  group:
    name: printadmin
    state: present

- name: Allow printadmin group to admin cups
  lineinfile:
    dest: /etc/cups/cups-files.conf
    regexp: '^SystemGroup'
    line: 'SystemGroup sys root printadmin'
    state: present

- name: Add users to cups
  user:
    name: "{{ user.name }}"
    groups: printadmin,lp
    append: yes

- name: Start and enable CUPS
  systemd:
    name: cups.socket
    enabled: yes
    state: started
