---
- name: Bootstrap Archlinux
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - "host_vars/{{ machine_aliases[ansible_product_name] }}"
  vars_prompt:
    - name: luks_passphrase
      prompt: "encryption passphrase (blank for no encryption):"
      private: yes
      confirm: yes
  roles:
    - { role: partition, tags: ['partition'] }
    - { role: mdadm, tags: ['mdadm'], when: mdadm_arrays is defined }
    - { role: encrypt, tags: ['encrypt'], when: luks_passphrase != '' }
    - { role: lvm, tags: ['lvm'], when: volume_groups is defined }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: mounts, tags: ['mounts'] }
    - { role: "arch-bootstrap", tags: ['bootstrap'] }
    - { role: luks-move-keyfiles, tags: ['encrypt'], when: luks_passphrase != '' }

- name: Install base system
  connection: chroot
  hosts: chroot
  vars_files:
    - "host_vars/{{ machine_aliases[ansible_product_name] }}"
  vars_prompt:
    - name: root_password
      prompt: "root password:"
      encrypt: "sha512_crypt"
      private: yes
      confirm: yes
    - name: user_password
      prompt: "user password:"
      encrypt: "sha512_crypt"
      private: yes
      confirm: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: user, tags: ['user'] }
    - { role: aur, tags: ['aur'] }
    - { role: dotfiles, tags: ['user'] }
    - { role: locales, tags: ['locales'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: thinkpad, tags: ['thinkpad'], when: "'ThinkPad' in ansible_product_version" }
    - { role: initramfs, tags: ['initramfs'] }
    - { role: networkmanager, tags: ['networkmanager'], when: static_ip is not defined }
    - { role: system_tools, tags: ['system_tools'] }
    - { role: grub, tags: ['grub'], when: bootloader == 'grub' }
    - { role: syslinux, tags: ['syslinux'], when: bootloader == 'syslinux' }

- name: Finish installation
  hosts: localhost
  connection: local
  vars_files:
    - "host_vars/{{ machine_aliases[ansible_product_name] }}"
  tasks:
    - name: unmount partitions with the new system
      command: umount -Rf {{ arch_root }}

    - name: unmount swap
      command: swapoff -a

    - name: close LUKS encrypted devices
      luks_device:
        device: "/dev/disk/by-id/{{ item.0.device_id }}-part{{ item.1.number }}"
        state: closed
      when: item.1.encrypt is defined and item.1.encrypt
      with_subelements:
        - "{{ sata_drives }}"
        - partitions

    # - name: reboot
      # command: reboot
