---
- name: Configure Arch
  hosts: hosts
  connection: local
  become: yes
  vars_files:
    - "host_vars/{{ machine_aliases[ansible_product_name] }}"
  roles:
    - { role: base, tags: ['base'] }
    - { role: aur, tags: ['aur'] }
    - { role: user, tags: ['user'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: networkmanager, tags: ['networkmanager'], when: static_ip is not defined }
    - { role: system_tools, tags: ['system_tools'] }
    - { role: pacman, tags: ['pacman'] }
    - { role: microcode, tags: ['microcode'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: thinkpad, tags: ['thinkpad'], when: "'ThinkPad' in ansible_product_version" }
    - { role: gnupg, tags: ['gnupg'] }
    - { role: laptop, tags: ['laptop'], when: "'ThinkPad' in ansible_product_version" }
    - { role: pulseaudio, tags: ['pulseaudio'], when: desktop is defined }
    - { role: x, tags: ['x'], when: desktop is defined }
    - { role: kde, tags: ['kde'], when: desktop is defined }
    - { role: sddm, tags: ['sddm'], when: desktop is defined }
    - { role: fonts, tags: ['fonts'], when: desktop is defined }
    - { role: browsers, tags: ['browsers'], when: desktop is defined }
    - { role: podman, tags: ['podman'], when: desktop is defined }
    - { role: dev-tools, tags: ['dev-tools'], when: desktop is defined }
    - { role: photography, tags: ['photography'], when: desktop is defined }
    - { role: videography, tags: ['videography'], when: desktop is defined }
    - { role: communication, tags: ['communication'], when: desktop is defined }
    # # - { role: firejail, tags: ['firejail'], when: desktop is defined }
    - { role: udisks, tags: ['udisks'], when: desktop is defined }
    - { role: cups, tags: ['cups'], when: desktop is defined }
    - { role: avahi, tags: ['avahi'], when: desktop is defined }
    - { role: gopass, tags: ['gopass'], when: desktop is defined }
    - { role: syncthing, tags: ['syncthing'], when: desktop is defined }
    - { role: media, tags: ['media'], when: desktop is defined }
    - { role: virtualbox, tags: ['virtualbox'], when: desktop is defined }

