---
- name: create user group
  group:
    name: "{{ user.group }}"
    state: present

- name: create user
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    append: yes
    groups: "{{ user.groups | join(',') }}"
    password: "{{ user_password }}"
    shell: "{{ user.shell }}"
    uid: "{{ user.uid }}"
    update_password: on_create
  when: user_password is defined

- name: Create user ssh dir
  file:
    path: /home/{{ user.name }}/.ssh
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0600

- include: sudo.yml
