---
- name: Install sudo
  pacman:
    name: sudo
    state: present

- name: configure sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 0440

- name: Set root password
  user:
    name: root
    password: "{{ root_password }}"
  when: root_password is defined

- name: lock root account
  command: passwd -l root
