---
- name: Install xfce
  pacman:
    name:
      - xfce4
      - xfce4-goodies
      - arc-gtk-theme
    state: present

- name: Install aur themes
  become: yes
  become_user: aurman
  aur:
    name:
      - numix-square-icon-theme-git
      # - numix-themes-archblue
      # - numix-icon-theme-git
      # - numix-square-icon-theme
      # - numix-circle-arc-icons-git
      # - numix-circle-icon-theme-git
    state: present
    
