---
- name: Install pulseaudio
  pacman:
    name: pulseaudio
    state: present

- name: Install pulsemixer
  pacman:
    name: pulsemixer
    state: present

- name: Install pavucontrol
  pacman:
    name: pavucontrol
    state: present

- name: Install tools for bluetooth
  pacman:
    name:
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - bluez-utils
    state: present

- name: Avoid resampling
  lineinfile:
    path: /etc/pulse/daemon.conf
    regexp: '; avoid-resampling'
    line: 'avoid-resampling = yes'

- name: Update sample rate
  lineinfile:
    path: /etc/pulse/daemon.conf
    regexp: '; default-sample-rate'
    line: 'default-sample-rate = 48000'

- name: Enable at login
  systemd:
    scope: user
    name: pulseaudio
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"

- name: Install pulseaudio panel for xfce
  pacman:
    name: xfce4-pulseaudio-plugin
    state: present
  when: "'xfce' in desktop"

- name: Push default.pa
  copy:
    src: default.pa
    dest: "/home/{{ user.name }}/.config/pulse/default.pa"

- name: Enable bluetooth at bluetooth
  ini_file:
    path: /etc/bluetooth/main.conf
    section: Policy
    option: AutoEnable
    value: "true"

- name: Start bluetooth
  systemd:
    name: bluetooth.service
    enabled: yes
    state: started
