---
- name: Install pulseaudio
  pacman:
    name: pulseaudio
    state: present

- name: Install pulsemixer
  pacman:
    name: pulsemixer
    state: present

- name: Install pavucontrol
  pacman:
    name: pavucontrol
    state: present

- name: Enable at login
  systemd:
    scope: user
    name: pulseaudio
    enabled: yes
    state: started
  become: yes
  become_user: "{{ item.name }}"
  loop: "{{ users }}"

- name: Install pulseaudio panel for xfce
  pacman:
    name: xfce4-pulseaudio-plugin
    state: present
  when: "'xfce' in desktop"

