---
- name: Install rcm
  become: yes
  become_user: aurman
  aur:
    name: rcm
    state: present

- name: Clone user dotfiles
  git:
    repo: "{{ user.dotfiles.url }}"
    dest: "/home/{{ user.name }}/{{ user.dotfiles.destination }}"
    accept_hostkey: yes
    update: no
  become: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  command: "rcup -d /home/{{ user.name}}/{{ user.dotfiles.destination}} {{ user.dotfiles.rcup_flags }}"
  become: yes
  become_user: "{{ user.name }}"

- name: Install antigen
  get_url:
    url: https://git.io/antigen
    dest: "/home/{{ user.name }}/.antigen.zsh"
  become: yes
  become_user: "{{ user.name }}"

- name: Install plugins
  command: "/bin/zsh -c 'source /home/{{ user.name }}/.zshrc; antigen reset'"
  become: yes
  become_user: "{{ user.name }}"
  changed_when: false
  failed_when: false

- name: Post install commands
  command: "/bin/zsh -c 'source /home/{{ user.name }}/.zshrc; {{ item }}'"
  become: yes
  become_user: "{{ user.name }}"
  changed_when: false
  failed_when: false
  loop: "{{ user.dotfiles.post_install_cmds }}"
