---
- name: Install bspwm
  pacman:
    name:
      - bspwm
      - dunst
      - picom
      - feh
      - slock
      - yad
    state: present

- name: Install polybar
  become: yes
  become_user: aurman
  aur:
    name: polybar

