---
- name: Install bspwm
  pacman:
    name: bspwm
    state: present

- name: Copy bspwmrc
  copy:
    src: bspwmrc
    dest: /home/{{ user.name }}/.config/bspwm/bspwmrc
    mode: 0770
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Install sxhkd
  pacman:
    name: sxhkd
    state: present

- name: Copy sxhkdrc
  copy:
    src: sxhkdrc
    dest: /home/{{ user.name }}/.config/sxhkd/sxhkdrc
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Install notifier
  pacman:
    name: dunst
    state: present

- name: Copy dunstrc
  copy:
    src: dunstrc
    dest: /home/{{ user.name }}/.config/dunst/dunstrc
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Install compositor
  pacman:
    name: picom
    state: present

- name: Install wallpaper manager
  pacman:
    name: feh
    state: present

- name: Install lock screen
  become: yes
  become_user: aurman
  aur:
    name: betterlockscreen
    state: present

- name: Install autolock tool
  become: yes
  become_user: aurman
  aur:
    name: xidlehook
    state: present

- name: Install script ui helper
  pacman:
    name: yad
    state: present

- name: Install mouse pointer hider
  pacman:
    name: unclutter
    state: present

- name: Install polybar
  become: yes
  become_user: aurman
  aur:
    name: polybar
    state: present

- name: Create polybar dir
  file:
    path: /home/{{ user.name }}/.config/polybar/
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Create polybar scripts dir
  file:
    path: /home/{{ user.name }}/.config/polybar/scripts
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Copy polybar config
  copy:
    src: polybar/config
    dest: /home/{{ user.name }}/.config/polybar/config
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Copy polybar launch
  copy:
    src: polybar/launch.sh
    dest: /home/{{ user.name }}/.config/polybar/launch.sh
    mode: 0770
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Copy polybar player script
  copy:
    src: polybar/scripts/player-mpris-simple.sh
    dest: /home/{{ user.name }}/.config/polybar/scripts/player-mpris-simple.sh
    mode: 0770
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Copy polybar pulseaudio script
  copy:
    src: polybar/scripts/pulseaudio-control.bash
    dest: /home/{{ user.name }}/.config/polybar/scripts/pulseaudio-control.bash
    mode: 0770
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

