---
- name: udisks2
  package:
    name: udisks2
    state: present

- name: ensure /media exits
  file:
    path: /media
    state: directory

- name: Install udiskie
  package:
    name: udiskie
    state: present

- name: Configure mounts
  copy: src=80-udisks2.rules dest=/etc/udev/rules.d/80-udisks2.rules

- name: Configure mount location
  template: src=99-udisks2.rules.j2 dest=/etc/udev/rules.d/99-udisks2.rules
