---
- name: Install Xorg
  pacman:
    name: xorg-server
    state: present

- name: Install Xinit
  pacman:
    name: xorg-xinit
    state: present

- name: Install xmodmap
  pacman:
    name: xorg-xmodmap
    state: present

- name: Install xdpyinfo
  pacman:
    name: xorg-xdpyinfo
    state: present

- name: Install xev
  pacman:
    name: xorg-xev
    state: present

- name: Install xorg-sessreg
  pacman:
    name: xorg-sessreg
    state: present

- name: Install xautomation
  pacman:
    name: xautomation
    state: present

- name: Install X driver(s)
  pacman:
    name: "{{ x_drivers }}"
    state: present

- name: Add user to video group
  user:
    name: "{{ user.name }}"
    groups: video
    append: yes

- name: Set keyboard layout
  shell: localectl set-x11-keymap gb

- include: shells.yml
- include: autorandr.yml
- include: srandrd.yml
