#! /bin/sh

# Managed by ansible

WALLPAPER="$HOME/Downloads/mando_2560x1080.jpg"

# Autostart
feh --bg-fill $WALLPAPER
sxhkd &
dunst &
unclutter &
xsetroot -cursor_name left_ptr
# NO_AT_BRIDGE=1 udiskie &
# urxvtd -q -f -o
xrdb ~/.Xresources
$HOME/.config/polybar/launch.sh &
picom &
# nm-applet &
# volctl &
xidlehook --not-when-audio --not-when-fullscreen --timer 360 "betterlockscreen -l" "" &
setxkbmap -option "ctrl:nocaps"

# Workspace
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Border
bspc config border_width 2

# Gap
bspc config window_gap   20

# Color
bspc config normal_border_color   "#282A36"
bspc config focused_border_color  "#BD93F9"
bspc config presel_feedback_color "#BD93F9"

# Monocule
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config single_monocle     true

# Float
bspc rule -a Yad                  state=floating
bspc rule -a Gimp                 state=floating
bspc rule -a mpv                  state=floating
bspc rule -a Zathura              state=tiled

# Workspaces
bspc rule -a Firefox              desktop='^9'    follow=on
bspc rule -a Slack                desktop='^8'    follow=on
