machine_aliases:
  20AWS37100: t440p.yml
  VirtualBox: vbox.yml
  'ProLiant MicroServer': hpn40l.yml
  'To be filled by O.E.M.': periwinkle.yml

locales:
  - en_GB

timezone: Europe/London

arch_root: /mnt

# File name for encryption key used by dmcrypt to encrypt non-root
# partitions. The key is stored on encrypted root partition which is unlocked
# with a password.
luks_keys_location: /etc/luks-keys

country: United Kingdom

user:
  name: craig
  uid: 1000
  group: craig
  shell: /usr/bin/zsh
  groups:
    - uucp
    - wheel
    - sys
    - video
    - systemd-journal
  password_store: git@github.com:cda0/password-store
  dotfiles:
    url: https://gitlab.com/cda0/dotfiles
    destination: .dotfiles
    rcup_flags: -fx README.md
    post_install_cmds:
      - goenv install 1.13.6
      - goenv global 1.13.6
      - pyenv install 3.8.1
      - pyenv virtualenv 3.8.1 neovim
      - pyenv activate neovim && pip install user neovim
      - nvm install v13
      - npm install -g neovim
      - rbenv install 2.7.0
      - rbenv global 2.7.0
      - gem install neovim

udisks:
  shared_mount: false

bootloader: grub

lightdm_greeter: lightdm-slick-greeter

passwordless_sudo: []

pacstrap_packages:
  - base
  - base-devel
  - ansible

base_packages:
  - base
  - base-devel
  - linux
  - linux-headers
  - linux-firmware
  - mdadm
  - lvm2

system_tools:
  - arch-wiki-lite
  - arch-wiki-docs
  - bat
  - ctags
  - fd
  - fzf
  - hwinfo
  - git
  - glances
  - exa
  - neofetch
  - nfs-utils
  # - neovim Add back in when neovim 0.5 is stable
  - openssh
  - ripgrep
  - tmux
  - youtube-dl

initramfs_hooks:
  - base
  - udev
  - autodetect
  - keyboard
  - keymap
  - consolefont
  - modconf
  - block
  - mdadm_udev
  - lvm2
  - encrypt
  - resume
  - filesystems
  - fsck

aur:
  dir: aur

base_fonts:
    - cantarell-fonts
    - gsfonts
    - noto-fonts
    - terminus-font
    - tex-gyre-fonts
    - ttf-caladea
    - ttf-carlito
    - ttf-dejavu
    - ttf-droid
    - ttf-inconsolata
    - ttf-liberation
    - ttf-opensans
    - ttf-ubuntu-font-family

aur_fonts:
    - ttf-courier-prime
    - ttf-heuristica
    - ttf-merriweather
    - ttf-merriweather-sans
    - ttf-oswald
    - ttf-quintessential
    - ttf-signika
    - powerline-fonts-git
    - nerd-fonts-source-code-pro
    - nerd-fonts-dejavu-complete
    - nerd-fonts-complete
