---
- name: Install gnupg
  pacman:
    name:
      - pinentry
      - gnupg
    state: present

- name: Copy gpg-agent.conf
  copy:
    src: gpg-agent.conf
    dest: "/home/{{ user.name }}/.gnupg/gpg-agent.conf"

- name: Enable gpg-agent
  systemd:
    name: gpg-agent.socket
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"

- name: Enable dirmngr
  systemd:
    name: dirmngr.socket
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"

- name: Enable gpg-agent-ssh
  systemd:
    name: gpg-agent-ssh.socket
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"

# If using SSH Auth add the keygrip to ~/.gnupg/sshcontrol with:
# gpg --list-keys --with-keygrip | grep -A 1 '\[A\]' | grep Keygrip | awk '{ print $3 }' > /home/{{ user.name }}/.gnupg/sshcontrol
