---
- name: Create luks dir
  file:
    path: "{{ arch_root }}{{ luks_keys_location }}"
    mode: '0700'
    state: directory

- name: Copy keyiles into place
  copy:
    src: "{{ item }}"
    dest: "{{ arch_root }}{{ luks_keys_location }}/"
    mode: 000
  with_fileglob:
    - "/*.keyfile"

- name: Shred precreated keys
  command: "shred -u {{ item }}"
  with_fileglob:
    - "/*.keyfile"

- name: Crypttab for raid
  crypttab:
    backing_device: "/dev/md/{{ item.name }}"
    name: "/dev/mapper/{{ item.name }}"
    state: present
    path: "{{ arch_root }}/etc/crypttab"
    opts: "{{ item.cryptopts | default(omit) }}"
    password: "{{ luks_keys_location }}/{{ item.name }}.keyfile"
  when: item.keyfile is defined and item.keyfile
  loop: "{{ mdadm_arrays }}"

