---
- include: tlp.yml

- name: Install powertop
  pacman:
    name: powertop
    state: present

- name: Install powerstat
  become: yes
  become_user: aurman
  aur:
    name: powerstat-git

# - name: Install battery-stats
  # become: yes
  # become_user: aurman
  # aur:
    # name: battery-stats-git

#- name: Install battop
#  become: yes
#  become_user: aurman
#  aur:
#    name: battop

