---
- name: configure initramfs build hooks
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: "HOOKS=({{ initramfs_hooks | join(' ') }})"

- name: rebuild initramfs
  command: mkinitcpio -p linux
  notify:
    - rebuild grub
  when: "'grub'in bootloader"

- name: restrict access permissions to initramfs
  file:
    path: "/boot/{{ item }}"
    mode: 0600
  loop:
    - initramfs-linux.img
    - initramfs-linux-fallback.img

