---
- include: root.yml

- name: Mount partition filesystems
  mount:
    path: "{{ arch_root }}{{ item.1.mountpoint }}"
    src: "/dev/disk/by-id/{{ item.0.device_id }}-part{{ item.1.number }}"
    fstype: "{{ item.1.filesystem }}"
    state: mounted
    opts: "{{ item.1.mount_opts|default(omit) }}"
  when: item.1.mountpoint is defined and "/" != item.1.mountpoint
  with_subelements:
    - "{{ sata_drives }}"
    - partitions

- name: Mount lvm filesystems
  mount:
    path: "{{ arch_root }}{{ item.1.mountpoint }}"
    src: "/dev/{{ item.0.name }}/{{ item.1.name }}"
    fstype: "{{ item.1.filesystem }}"
    opts: "{{ item.1.mount_opts|default(omit) }}"
    state: mounted
  when: item.1.mountpoint is defined and "/" != item.1.mountpoint
  with_subelements:
    - "{{ volume_groups }}"
    - logical_volumes

- name: Mount raid
  mount:
    path: "{{ arch_root }}{{ item.mountpoint }}"
    src: "/dev/mapper/{{ item.mapper_name }}"
    fstype: "{{ item.filesystem }}"
    opts: "{{ item.mount_opts|default(omit) }}"
    state: mounted
  when: mdadm_arrays is defined and item.mountpoint is defined
  loop: "{{ mdadm_arrays }}"
