---
- name: Install discord
  pacman:
    name: discord
    state: present

- name: Install slack
  become: yes
  become_user: aurman
  aur:
    name: slack-desktop
    state: present

- name: Install weechat
  pacman:
    name: weechat
    state: present

- name: Install newsboat
  pacman:
    name: newsboat
    state: present
