---
- name: Firefox
  pacman:
    name: firefox
    state: present

- name: Brave
  become: yes
  become_user: aurman
  aur:
    name: brave-bin
    skip_installed: yes

- name: Qutebrowser
  pacman:
    name: qutebrowser
    state: present
