---
- name: Install tlp
  pacman:
    name: tlp
    state: present

- name: Start tlp
  systemd:
    name: tlp.service
    enabled: yes
    state: started

- name: Start and enabled tlp sleep
  systemd:
    name: tlp-sleep.service
    enabled: yes
    state: started

