---
- name: Create partition filesystems
  filesystem:
    fstype: "{{ item.1.filesystem }}"
    dev: "/dev/disk/by-id/{{ item.0.device_id }}-part{{ item.1.number }}"
  when: item.1.filesystem is defined and item.1.filesystem != "swap"
  with_subelements:
    - "{{ sata_drives }}"
    - partitions

- name: Create lvm filesystems
  filesystem:
    fstype: "{{ item.1.filesystem }}"
    dev: "/dev/{{ item.0.name }}/{{ item.1.name }}"
  when: item.1.filesystem is defined and item.1.filesystem != "swap"
  with_subelements:
    - "{{ volume_groups }}"
    - logical_volumes

- include: swap.yml
