---
- name: Install mpv
  package: name=mpv state=present

- name: Install mopidy and ncmpcpp
  package:
    name:
      - mopidy
      - ncmpcpp
      - gnu-netcat
    state: present

- name: Install mopidy spotify
  become: yes
  become_user: aurman
  aur:
    name:
      - mopidy-spotify
      - mopidy-mpd

- name: Push service file
  copy:
    src: mopidy.service
    dest: /etc/systemd/user/mopidy.service

- name: Start and enable mopidy.service
  systemd:
    scope: user
    name: mopidy.service
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"

- name: Install spotifyd
  pacman:
    name: spotifyd
    state: present

- name: Install spotify-tui
  become: yes
  become_user: aurman
  aur:
    name: spotify-tui
    state: present

- name: Start and enable spotifyd
  systemd:
    scope: user
    name: spotifyd.service
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"

  # TODO: Add spotify files here with ansible vault secrets
