---
- name: Install acpi_call for TLP battery functions
  pacman:
    name: acpi_call
    state: present
  tags:
    - battery

- name: Install tpacpi-bat
  pacman:
    name: tpacpi-bat
    state: present
  tags:
    - battery
