hostname: aurora

keymap: uk
consolefont: Lat2-Terminus16

bootloader: syslinux

static_ip: 192.168.1.12

sata_drives:
  - device: /dev/disk/by-id/ata-WDC_WD2500AAKS-00VSA0_WD-WMART1094011
    table: msdos
    partitions:
      - number: 1
        start: 0%
        end: 512MiB
        flags: [boot]
        filesystem: ext2
        mountpoint: /boot

      - number: 2
        start: 512MiB
        end: 100%
        filesystem: ext4
        opts: ^has_journal
        mountpoint: /
