hostname: periwinkle

keymap: uk
consolefont: Lat2-Terminus16

bootloader: grub
bootloader_type: bios

desktop: plasma

x_drivers:
  - xf86-video-amdgpu
  - mesa
  - vulkan-radeon
  - libva-mesa-driver

extra_packages:

kernel_cmdline:

data_disks:
- devices:
  - /dev/disk/by-id/ata-OCZ-VERTEX4_OCZ-2193L1V5Z0F5JE34
  partition_number: 1
  partition_start: 0%
  partition_end: 1MiB
  partition_name: bios
  partition_flags: [bios_grub]
- path: /boot
  devices:
  - /dev/disk/by-id/ata-OCZ-VERTEX4_OCZ-2193L1V5Z0F5JE34
  partition_number: 2
  partition_start: 1MiB
  partition_end: 512MiB
  partition_name: boot
  fs_type: vfat
- devices:
  - /dev/disk/by-id/ata-OCZ-VERTEX4_OCZ-2193L1V5Z0F5JE34
  partition_number: 3
  partition_start: 512MiB
  partition_end: 100%
  partition_name: cryptlvm
  partition_flags: [lvm]
  encrypt: true
  encrypt_name: cryptlvm
  type: lvm
  cryptroot_device: true
- devices:
  - /dev/mapper/cryptlvm
  type: lvm_vg
  lvm_vg_name: vg00
- path: /
  type: lvm_lv
  fs_type: ext4
  size: 32G
  lvm_vg: vg00
  lvm_lv_name: root
- path: /home
  type: lvm_lv
  fs_type: ext4
  size: 100%FREE
  lvm_vg: vg00
  lvm_lv_name: home
