hostname: moana

keymap: uk
consolefont: Lat2-Terminus16

bootloader: grub

desktop: bspwm

x_drivers:
  - xf86-input-synaptics
  - mesa
  - vulkan-intel

extra_packages:
  - dhcpcd
  - net-tools
  - wireless_tools
  - wpa_supplicant

kernel_cmdline: 'acpi_osi= i915 modeset=1'

root_device: ata-TS120GMTS420S_F586330108-part3

sata_drives:
- device_id: ata-TS120GMTS420S_F586330108
  ssd: true
  table: gpt
  partitions:
  - name: bios
    number: 1
    start: 0%
    end: 1MiB
    flags: [bios_grub]
  - name: efi
    number: 2
    start: 1MiB
    end: 512MiB
    flags: [esp]
    filesystem: vfat
    mountpoint: /boot
  - name: cryptlvm
    number: 3
    start: 512MiB
    end: 100%
    flags: [lvm]
    encrypt: true
- device_id: ata-TOSHIBA_MK5061GSYN_X2OCY0Z5F
  table: gpt
  partitions:
  - name: raid
    number: 1
    start: 0%
    end: 100%
    flags: [raid]
- device_id: ata-ST500LM021-1KJ152_W622TAES
  table: gpt
  partitions:
  - name: raid
    number: 1
    start: 0%
    end: 100%
    flags: [raid]

mdadm_arrays:
- name: md00
  devices:
  - /dev/disk/by-id/ata-TOSHIBA_MK5061GSYN_X2OCY0Z5F-part1
  - /dev/disk/by-id/ata-ST500LM021-1KJ152_W622TAES-part1
  level: 1
  encrypt: true
  keyfile: true
  state: present

volume_groups:
- name: vg00
  pvs:
  - /dev/mapper/cryptlvm
  logical_volumes:
  - name: root
    size: 32G
    filesystem: ext4
    mountpoint: /
  - name: swap
    size: 20G
    filesystem: swap
  - name: home
    size: 100%FREE
    filesystem: ext4
    mountpoint: /home
- name: vg01
  pvs:
  - /dev/mapper/md00
  logical_volumes:
  - name: data
    size: 100%FREE
    filesystem: ext4
    mountpoint: /data

