hostname: moana

keymap: uk
consolefont: Lat2-Terminus16

bootloader: grub
bootloader_type: uefi

desktop: plasma

x_drivers:
  - xf86-input-synaptics
  - mesa
  - vulkan-intel

extra_packages:
  - dhcpcd
  - net-tools
  - wireless_tools
  - wpa_supplicant

kernel_cmdline: 'acpi_osi= i915 modeset=1'

data_disks:
- devices:
  - /dev/disk/by-id/ata-TS120GMTS420S_F586330108
  partition_number: 1
  partition_start: 0%
  partition_end: 1MiB
  partition_name: bios
  partition_flags: [bios_grub]
- path: /boot
  devices:
  - /dev/disk/by-id/ata-TS120GMTS420S_F586330108
  partition_number: 2
  partition_start: 1MiB
  partition_end: 512MiB
  partition_name: efi
  partition_flags: [esp]
  fs_type: vfat
- devices:
  - /dev/disk/by-id/ata-TS120GMTS420S_F586330108
  partition_number: 3
  partition_start: 512MiB
  partition_end: 100%
  partition_name: cryptlvm
  partition_flags: [lvm]
  encrypt: true
  encrypt_name: cryptlvm
  type: lvm
  cryptroot_device: true
- devices:
  - /dev/disk/by-id/ata-ST500LM021-1KJ152_W622TAES
  - /dev/disk/by-id/ata-TOSHIBA_MK5061GSYN_X2OCY0Z5F
  type: raid
  mdadm_level: 1
  mdadm_name: md00
  partition_number: 1
  partition_start: 0%
  partition_end: 100%
  partition_name: md00
  partition_flags: [raid]
  encrypt: true
  encrypt_keyfile: true
  encrypt_name: cryptmd00
- devices:
  - /dev/mapper/cryptlvm
  type: lvm_vg
  lvm_vg_name: vg00
- devices:
  - /dev/mapper/cryptmd00
  type: lvm_vg
  lvm_vg_name: vg01
- path: /
  type: lvm_lv
  fs_type: ext4
  size: 32G
  lvm_vg: vg00
  lvm_lv_name: root
- type: lvm_lv
  fs_type: swap
  size: 20G
  lvm_vg: vg00
  lvm_lv_name: swap
- path: /home
  type: lvm_lv
  fs_type: ext4
  size: 100%FREE
  lvm_vg: vg00
  lvm_lv_name: home
- path: /data
  type: lvm_lv
  fs_type: ext4
  size: 100%FREE
  lvm_vg: vg01
  lvm_lv_name: data
