hostname: ralph

keymap: uk
consolefont: Lat2-Terminus16

bootloader: grub

kernel_cmdline: ''

sata_drives:
  - device: /dev/disk/by-id/ata-VBOX_HARDDISK_VB0176b4df-97b2b1b4
    table: gpt
    partitions:
      - name: bios
        number: 1
        start: 0%
        end: 1MiB
        flags: [bios_grub]

      - name: efi
        number: 2
        start: 1MiB
        end: 512MiB
        flags: [esp]
        filesystem: vfat
        mountpoint: /efi

      - name: root
        number: 3
        start: 512MiB
        end: 100%
        flags: [lvm]
        encrypt: true

  - device: /dev/disk/by-id/ata-VBOX_HARDDISK_VBe0a2506b-cbf5cf12
    table: gpt
    partitions:
      - name: raid
        number: 1
        start: 0%
        end: 100%
        flags: [raid]

  - device: /dev/disk/by-id/ata-VBOX_HARDDISK_VBfa4ac439-80d6f65d
    table: gpt
    partitions:
      - name: raid
        number: 1
        start: 0%
        end: 100%
        flags: [raid]

mdadm_arrays:
  - name: cryptmd0
    mapper_name: md0
    devices:
      - /dev/disk/by-id/ata-VBOX_HARDDISK_VBe0a2506b-cbf5cf12-part1
      - /dev/disk/by-id/ata-VBOX_HARDDISK_VBfa4ac439-80d6f65d-part1
    filesystem: ext4
    level: 1
    encrypt: true
    mountpoint: /data
    state: present
    keyfile: true

volume_groups:
  - name: vgroot
    pvs:
      - /dev/disk/by-id/ata-VBOX_HARDDISK_VB0176b4df-97b2b1b4-part3

logical_volumes:
  - name: cryptroot
    volume_group: vgroot
    mapper_name: root
    size: 4G
    filesystem: ext4
    mountpoint: /
    encrypt: true
    use_passphrase: true
    keyfile: true
  - name: cryptswap
    volume_group: vgroot
    mapper_name: swap
    size: 1G
    filesystem: swap
    encrypt: true
    use_passphrase: true
    keyfile: true
  - name: crypthome
    volume_group: vgroot
    mapper_name: home
    size: 100%FREE
    keyfile: true
    filesystem: ext4
    mountpoint: /home
    encrypt: true
    shrink: no
