---
- name: Install ssmtp
  become: yes
  become_user: aurman
  aur:
    name: ssmtp
    state: present

- name: Copy config file
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    mode: 0644

- name: Copy aliases file
  template:
    src: revaliases.j2
    dest: /etc/ssmtp/revaliases
    mode: 0644
    
- name: Install raid check
  become: yes
  become_user: aurman
  aur:
    name: raid-check-systemd
    state: present

- name: Enable and start raid-check service
  service:
    name: raid-check.service
    enabled: yes
    state: started
  tags:
    - mdadm

- name: Enable and start raid-check timer
  service:
    name: raid-check.service
    enabled: yes
    state: started
  tags:
    - mdadm