---
- name: Install reflector
  pacman:
    name: reflector
    state: present

- name: Configure repository mirrors
  command: "reflector --sort rate --completion-percent 98 -p https --country '{{ country }}' --save /etc/pacman.d/mirrorlist"

- name: Install base packages
  pacman:
    name: "{{ base_packages }}"
    state: present

- name: Install extra packages
  pacman:
    name: "{{ extra_packages }}"
  when: extra_packages is defined
