---
- name: Install reflector
  pacman:
    name: reflector
    state: present

- name: Configure repository mirrors
  command: "reflector --sort rate --completion-percent 98 -p https --country '{{ country }}' --save /etc/pacman.d/mirrorlist"

- name: Upgrade system to latest state
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install base packages
  pacman:
    name: "{{ base_packages }}"
    state: present
