---
- name: Install hdparm
  pacman:
    name: hdparm
    state: present

- name: Enable and start weekly filesystem TRIM timer
  service:
    name: fstrim.timer
    enabled: yes
    state: started
  when: item.ssd is true
  loop: "{{ sata_drives }}"
