---
- name: Check status of existing arrays
  shell: "mdadm --detail --scan | grep {{ item.name }}"
  register: mdadm_scan
  changed_when: false
  failed_when: false
  loop: "{{ mdadm_arrays }}"

- name: create raid
  shell: "yes | mdadm --create /dev/md/{{ item.name }} --level={{ item.level }} --raid-devices={{ item.devices|count }} {{ item.devices|join(' ') }}"
  when: mdadm_scan.results[0].rc != 0
  register: array_created
  loop: "{{ mdadm_arrays }}"

