---
- name: Check status of existing arrays
  shell: "set -o pipefail && mdadm --detail --scan | grep {{ item.mdadm_name }}"
  register: mdadm_scan
  changed_when: false
  failed_when: false
  loop: "{{ mdadm_arrays }}"

- name: create raid
  shell: |
    set -o pipefail && yes |
    mdadm --create /dev/md/{{ item.mdadm_name }} --level={{ item.mdadm_level }} --raid-devices={{ item.devices|count }} {{ item.devices|join(' ') }}
  when: mdadm_scan.results[0].rc != 0
  register: array_created
  loop: "{{ mdadm_arrays }}"

