---
- name: Mount root
  mount:
    path: "{{ arch_root }}{{ item.path }}"
    src: "{% if type == 'lvm_lvm'%}/dev/{{ lvm_vg }}/{{ lvm_lv_name }}{% else %}{{ item.devices[0] }}{% endif %}"
    fstype: "{{ item.fs_type }}"
    state: mounted
    opts: "{{ item.1.mount_opts|default(omit) }}"
  loop: "{{ root_fs }}"

- name: Mount other filesystems
  mount:
    path: "{{ arch_root }}{{ item.path }}"
    src: "{% if type == 'lvm_lvm'%}/dev/{{ lvm_vg }}/{{ lvm_lv_name }}{% else %}{{ item.devices[0] }}{% endif %}"
    fstype: "{{ item.fs_type }}"
    state: mounted
    opts: "{{ item.1.mount_opts|default(omit) }}"
  loop: "{{ other_mounts }}"

