---
- name: Install NetworkManager
  pacman:
    name:
      - networkmanager
      - network-manager-applet
    state: present

- name: enable services
  systemd:
    name: NetworkManager.service
    enabled: yes
