---
- name: Create LVM groups
  lvg:
    pvs: "{{ item.pvs | join(',') }}"
    vg: "{{ item.name }}"
    state: present
  loop: "{{ volume_groups }}"

- name: Create LVM Volumes
  lvol:
    vg: "{{ item.0.name }}"
    lv: "{{ item.1.name }}"
    size: "{{ item.1.size }}"
    shrink: "{{ item.1.shrink | default(omit) }}"
    state: present
  with_subelements:
    - "{{ volume_groups }}"
    - logical_volumes
